services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    env_file:
      - .env
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: always
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  ollama:
  open-webui:
